# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright 2016 Prabhu Vignesh Kumar Rajagopal <prabhu.vignesh1990@gmail.com>

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Vagrant.configure(2) do |config|
 
  config.vm.hostname = "gluu"

  config.vm.box = "ubuntu/trusty64"

  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "172.28.128.49"
  #config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.synced_folder "C:\\Users\\prabhukumar\\Documents\\workspace", "/home/vicky/Documents"

   config.vm.provider "virtualbox" do |vb|
     # vb.gui = true
  
     # Customize the amount of memory on the VM:
     vb.memory = "4200"
   end

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

 # config.vm.provision "shell", inline: <<-SHELL
 #  sudo echo "deb https://repo.gluu.org/ubuntu/ trusty main" > /etc/apt/sources.list.d/gluu-repo.list
 #  sudo curl https://repo.gluu.org/ubuntu/gluu-apt.key | apt-key add -
 #  sudo apt-get -y update
 #  sudo apt-get -y install gluu-server-2.4.4
 # SHELL
end
