
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright 2016 Prabhu Vignesh Kumar Rajagopal <prabhu.vignesh1990@gmail.com>


Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  # Port forwarding
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 4200, host: 4200
  config.vm.network "forwarded_port", guest: 7050, host: 7050
  config.vm.network "forwarded_port", guest: 7051, host: 7051
  config.vm.network "forwarded_port", guest: 7053, host: 7053
  config.vm.network "forwarded_port", guest: 7054, host: 7054  
  config.vm.network "forwarded_port", guest: 7070, host: 7070
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.network "private_network", ip: "172.28.128.90"


  config.vm.synced_folder "C:\\Users\\prabhukumar\\Documents\\workspace", "/home/vicky/Documents", type: "nfs"


  # VirtualBox configuration
  config.vm.provider "virtualbox" do |vb|
    # Increase memory allocated to vm (for build tasks)
    vb.memory = 6192
  end


  # Install prereqs
  config.vm.provision "provision-root", type: "shell", path: "provision-root.sh"
  config.vm.provision "provision-user", type: "shell", path: "provision-user.sh", privileged: false
end
