# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright 2016 Prabhu Vignesh Kumar Rajagopal <prabhu.vignesh1990@gmail.com>

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Vagrant.configure(2) do |config|
 
  config.vm.hostname = "survey"

  config.vm.box = "limesurvey"
  #box location https://vagrantcloud.com/brunofpereira/boxes/ubuntu-limesurvey/versions/1.2/providers/virtualbox.box
# MySQL Credentials: root:123qweASD#
# LimeSurvey Credentials: admin:password
# By default the machine will be appear as another physical device on your network.


  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "172.28.128.92"
  #config.vm.network :forwarded_port, guest: 22, host: 2200, id: "ssh"
  config.vm.synced_folder "C:\\Users\\prabhukumar\\Documents\\workspace", "/home/vicky/Documents"

   config.vm.provider "virtualbox" do |vb|
     # vb.gui = true
  
     # Customize the amount of memory on the VM:
     vb.memory = "512"
   end

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

   # config.vm.provision "shell", inline: <<-SHELL
   #   sudo apt-get update
   #   sudo apt-get install -y apache2
   # SHELL
end
