# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright 2016 Prabhu Vignesh Kumar Rajagopal <prabhu.vignesh1990@gmail.com>


Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "gitserver"
   config.vm.box_check_update = false
   #config.ssh.forward_agent = true

  # config.vm.network "forwarded_port", guest: 80, host: 8080

   config.vm.network "private_network", ip: "172.28.128.21"

  # config.vm.network "public_network"
  config.vm.synced_folder "/home/vicky/Documents", "/home/vicky/Documents"

  # config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
  #
  #   vb.memory = "1024"
  # end


  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

#	   config.vm.provision "shell", inline:<<-SHELL
#	     sudo apt-get update
#	     sudo apt-get install git-core
#	     sudo useradd git
#	     sudo passwd git
#	     		
#	   SHELL
end
