# -*- mode: ruby -*-
# vi: set ft=ruby :

# Copyright 2016 Prabhu Vignesh Kumar Rajagopal <prabhu.vignesh1990@gmail.com>

Vagrant.configure(2) do |config|
 
  config.vm.hostname = "nagiosserver"

  config.vm.box = "ubuntu/trusty64"

  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "172.28.128.23"
 # config.vm.synced_folder "/home/vicky/Documents", "/home/vicky/Documents"


  # config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
  #
  #   vb.memory = "1024"
  # end

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

   config.vm.provision "shell", inline: <<-SHELL
      sudo useradd nagios
      sudo groupadd nagcmd
      sudo usermod -a -G nagcmd nagios
      sudo apt-get update
      sudo apt-get install build-essential libgd2-xpm-dev openssl libssl-dev xinetd apache2-utils unzip
      cd ~
      curl -L -O https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.1.1.tar.gz
      tar xvf nagios-*.tar.gz
      cd nagios-*
      ./configure --with-nagios-group=nagios --with-command-group=nagcmd 
      make all  
      sudo make install
      sudo make install-commandmode
      sudo make install-init
      sudo make install-config
      sudo /usr/bin/install -c -m 644 sample-config/httpd.conf /etc/apache2/sites-available/nagios.conf
      sudo usermod -G nagcmd www-data
      cd ~
      curl -L -O http://nagios-plugins.org/download/nagios-plugins-2.1.1.tar.gz
      tar xvf nagios-plugins-*.tar.gz
      cd nagios-plugins-*
      ./configure --with-nagios-user=nagios --with-nagios-group=nagios --with-openssl
      make
      sudo make install
      cd ~
      curl -L -O http://downloads.sourceforge.net/project/nagios/nrpe-2.x/nrpe-2.15/nrpe-2.15.tar.gz
      tar xvf nrpe-*.tar.gz
      cd nrpe-*
      ./configure --enable-command-args --with-nagios-user=nagios --with-nagios-group=nagios --with-ssl=/usr/bin/openssl --with-ssl-lib=/usr/lib/x86_64-linux-gnu
      make all
      sudo make install
      sudo make install-xinetd
      sudo make install-daemon-config
      sudo vi /etc/xinetd.d/nrpe
      only_from = 127.0.0.1 10.132.224.168
      sudo service xinetd restart
   SHELL
end
