# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright 2016 Prabhu Vignesh Kumar Rajagopal <prabhu.vignesh1990@gmail.com>

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Vagrant.configure(2) do |config|
 
  config.vm.hostname = "dockerbase"

  config.vm.box = "ubuntu/trusty64"

  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "172.28.128.57"
  config.vm.synced_folder "C:\\Users\\prabhukumar\\Documents\\workspace", "/home/vicky/Documents"

   config.vm.provider "virtualbox" do |vb|
     # vb.gui = true
     # Customize the amount of memory on the VM:
     vb.memory = "4048"
   end

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  #config.vm.provision "shell", inline: <<-SHELL
  # sudo apt-get -y update
  # sudo apt-get install apt-transport-https ca-certificates
  # sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  # echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
  # sudo apt-get -y update
  # sudo apt-cache policy docker-engine
  # sudo apt-get -y install linux-image-extra-$(uname -r) linux-image-extra-virtual
  # sudo apt-get -y install docker-engine
  #SHELL
end
