# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright 2016 Prabhu Vignesh Kumar Rajagopal <prabhu.vignesh1990@gmail.com>

Vagrant.configure(2) do |config|
 
  config.vm.hostname = "mongodb"

  config.vm.box = "ubuntu/trusty64"

  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "172.28.128.38"
#  config.vm.synced_folder "/home/vicky/Documents", "/home/vicky/Documents"

   config.vm.provider "virtualbox" do |vb|
     # vb.gui = true
  
     # Customize the amount of memory on the VM:
     vb.memory = "512"
   end

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

#  config.vm.provision "shell", inline: <<-SHELL
#    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
#    echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list     sudo apt-get update
#    sudo apt-get update
#    sudo apt-get install -y mongodb-org
#    echo "mongodb-org hold" | sudo dpkg --set-selections
#    echo "mongodb-org-server hold" | sudo dpkg --set-selections
#    echo "mongodb-org-shell hold" | sudo dpkg --set-selections
#    echo "mongodb-org-mongos hold" | sudo dpkg --set-selections
#    echo "mongodb-org-tools hold" | sudo dpkg --set-selections
#    sudo service mongod start

#  SHELL
end
