# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright 2016 Prabhu Vignesh Kumar Rajagopal <prabhu.vignesh1990@gmail.com>

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ansiblerun"
    config.vm.box_check_update = false
    config.ssh.forward_agent = true

  # config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.network "private_network", ip:"172.28.128.10"

  # config.vm.network "public_network"

    config.vm.synced_folder "C:\\Users\\prabhukumar\\Documents\\workspace", "/home/vicky/Documents", type: "nfs"

  # config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end


#  config.vm.provision "shell", inline: <<-SHELL
#    sudo apt-add-repository ppa:ansible/ansible -y
#    sudo apt-get update && sudo apt-get install ansible -y
#  SHELL
end
