# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright 2016 Prabhu Vignesh Kumar Rajagopal <prabhu.vignesh1990@gmail.com>


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vm.synced_folder "C:\\Users\\prabhukumar\\Documents\\workspace", "/home/vicky/Documents", type: "nfs"
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get -y update
  #   sudo apt-get -y install apt-transport-https ca-certificates
  #   sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  #   echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
  #   sudo apt-get -y update
  #   sudo apt-cache policy docker-engine
  #   sudo apt-get -y install linux-image-extra-$(uname -r) linux-image-extra-virtual
  #   sudo apt-get -y install docker-engine
  # SHELL

  config.vm.define "dockernode1" do |dockernode1|
      dockernode1.vm.hostname = "dockernode1"
      dockernode1.vm.network "private_network", ip: "172.28.128.53"
      dockernode1.vm.provider :virtualbox do |vb|
          vb.memory = "512"
      end
  end

  config.vm.define "dockernode2" do |dockernode2|
      dockernode2.vm.hostname = "dockernode2"
      dockernode2.vm.network "private_network", ip: "172.28.128.54"
      dockernode2.vm.provider :virtualbox do |vb|
          vb.memory = "512"
      end
  end

    config.vm.define "dockernode3" do |dockernode3|
      dockernode3.vm.hostname = "dockernode3"
      dockernode3.vm.network "private_network", ip: "172.28.128.55"
      dockernode3.vm.provider :virtualbox do |vb|
          vb.memory = "512"
      end
  end



  config.vm.define "dockerclient" do |dockerclient|
      dockerclient.vm.hostname = "dockerclient"
      dockerclient.vm.network "private_network", ip: "172.28.128.56"
      dockerclient.vm.provider :virtualbox do |vb|
          vb.memory = "512"
      end
  end

end
