# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright 2016 Prabhu Vignesh Kumar Rajagopal <prabhu.vignesh1990@gmail.com>


Vagrant.configure(2) do |config|
  config.vm.hostname = "rhel71"
  config.vm.box = "thussain/rhel7"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "172.28.128.40"
  # config.vm.network "public_network"

   config.vm.synced_folder "/home/vicky/Documents", "/home/vicky/Documents"

#  config.vm.provider "virtualbox" do |vb|
#     # vb.gui = true
#  
#     vb.memory = "1024"
#  end


  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
