# -*- mode: ruby -*-
# vi: set ft=ruby :

# Copyright 2016 Prabhu Vignesh Kumar Rajagopal <prabhu.vignesh1990@gmail.com>
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Vagrant.configure(2) do |config| 

  #config.vm.box = "bento/ubuntu-16.04"
  #config.vm.box = "geerlingguy_ubuntu1604"
  config.vm.box = "ubuntu_xenial"

  config.vm.box_check_update = false
  config.vm.synced_folder "C:\\Users\\prabhukumar\\Documents\\workspace", "/home/vicky/Documents"
  config.vm.define "openstack" do |openstack|
      openstack.vm.hostname = "openstack"
      openstack.vm.network "private_network", ip: "172.28.128.90"
      openstack.vm.provider :virtualbox do |vb|
          vb.memory = "4094"
      end
  end

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

   # config.vm.provision "shell", inline: <<-SHELL
   #   sudo apt-get update
   #   sudo apt-get install -y lighttpd
   # SHELL
end
