# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.box_check_update = false

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "172.28.128.84"
  config.vm.synced_folder "C:\\Users\\prabhukumar\\Documents\\workspace", "/home/vicky/Documents", type: "nfs"


  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = 'provision/chef/cookbooks'
    chef.add_recipe 'java'
    chef.json           = {
        :java  => {
            :jdk_version    => 7,
            :install_flavor => 'oracle',
            'oracle' => {
                'accept_oracle_download_terms' => true
            }
        }
    }
  end
  config.vm.provision 'shell', path: 'provision/shell/script.sh'
end




#
#    ## Jenkins
#    http://172.28.128.84:8080
#    
#    ## Sonar
#    http://172.28.128.84:9000
#    admin/admin
